mailing/mailing/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include('createmailing.urls', namespace='createmailing')),
]

mailing/product/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'product'

urlpatterns = [
    url(r'track_email_open/(?P<tracking_id>[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})/', views.track_email_open, name='track_email_open'),
    url(r'^create_order', views.create_order, name="create_order"),
    # url(r'^', views.create_order, name="create_order"),
] 

mailing/templates/includes/create_order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="card">
    <h2 class="text-center">Создать рассылку подписчикам</h2>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#CreateModal">
      <div class="card ms-5 me-5 mb-5 mt-5">
        <p>Введи заголовок</p>
        <p>Email отправителя</p>
        <p>Текст письма</p>
      </div>
    </button>
  </div>

  <!-- modal window -->
  <div class="modal fade" id="CreateModal" tabindex="-1" aria-labelledby="CreateModalLabel">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <!-- modal header -->
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="CreateModalLabel">Заполните письмо</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!-- modal body -->
        <div class="modal-body">
          <form id="InputForm" method="post" data-url="{% url 'createmailing:create_order' %}">
            {% csrf_token %}
            {{ form.as_table }}
          </form>
        </div>
        <!-- modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" form="InputForm" class="btn btn-primary">Create Order</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailing/templates/includes/create_order_test.html
{% block content %}
    <h2>Create a new order</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Order</button>
    </form>
{% endblock %}

mailing/templates/includes/test.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="card">
    <h2 class="text-center">Создать рассылку</h2>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <div class="card ms-5 me-5 mb-5 mt-5">
        <p>Введи заголовок</p>
        <p>Email отправителя</p>
        <p>Текст письма</p>
        <p>Email адресса через запятую</p>
      </div>
    </button>
  </div>

  <!-- modal window -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <!-- modal header -->
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Заполните письмо</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!-- modal body -->
        <div class="modal-body">
          <form id="myForm" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <button type="submit">Create Order</button>
          </form>
        </div>
        <!-- modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}